on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Compile and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
          - stable
          - 1.31.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check --all --verbose
      - uses: actions-rs/cargo@v1
        with:
          command: build --all --verbose
      - uses: actions-rs/cargo@v1
        with:
          command: test --all --verbose

  api-docs:
    name: Publish API Docs to GitHub Pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: doc --all --verbose
      - name: Redirect top-level GitHub Pages
        run: "echo '<meta http-equiv=\"refresh\" content=\"0; url=stateful_native_library/index.html\" />' > target/doc/index.html"
        shell: bash
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          build_dir: "target/doc"